version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8011:8080"
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_NAME=api_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - LIBS_DIRECTORY=/opt/api_db/libs
    depends_on:
      - db_postgres

  db_postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_db