"""empty message

Revision ID: a5ad0487ce36
Revises: bed4a1c6015a
Create Date: 2023-04-26 11:12:54.228076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ad0487ce36'
down_revision = 'bed4a1c6015a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_sessions', sa.Column('actuality_dttm', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_sessions', 'actuality_dttm')
    # ### end Alembic commands ###
