"""empty message

Revision ID: bed4a1c6015a
Revises: 696f0afadf92
Create Date: 2023-04-24 18:14:04.858527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed4a1c6015a'
down_revision = '696f0afadf92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_statuses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status', name='status_key')
    )
    op.create_table('callee',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=512), nullable=False),
    sa.Column('push_token', sa.VARCHAR(length=512), nullable=True),
    sa.Column('actuality_dttm', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('caller_id', sa.BigInteger(), nullable=False),
    sa.Column('callee_id', sa.BigInteger(), nullable=False),
    sa.Column('call_session_initiation_dttm', sa.TIMESTAMP(), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['callee_id'], ['callee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['caller_id'], ['caller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caller_id', 'callee_id', 'call_session_initiation_dttm', name='calls_caller_id_callee_id_call_session_initiation_dttm_key'),
    sa.UniqueConstraint('caller_id', 'callee_id', 'delay', name='calls_caller_id_callee_id_delay_key')
    )
    op.create_table('calls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('caller_id', sa.BigInteger(), nullable=False),
    sa.Column('callee_id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('call_started_dttm', sa.TIMESTAMP(), nullable=False),
    sa.Column('call_ended_dttm', sa.TIMESTAMP(), nullable=False),
    sa.Column('actuality_dttm', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['callee_id'], ['callee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['caller_id'], ['caller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['call_statuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caller_id', 'callee_id', 'call_ended_dttm', name='calls_caller_id_callee_id_call_ended_dttm_key'),
    sa.UniqueConstraint('caller_id', 'callee_id', 'call_started_dttm', name='calls_caller_id_callee_id_call_started_dttm_key')
    )
    op.alter_column('caller', 'push_token',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.drop_column('caller', 'ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caller', sa.Column('ip', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.alter_column('caller', 'push_token',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_table('calls')
    op.drop_table('call_sessions')
    op.drop_table('callee')
    op.drop_table('call_statuses')
    # ### end Alembic commands ###
