"""empty message

Revision ID: 8944d8fb009e
Revises: a5ad0487ce36
Create Date: 2023-04-26 11:31:02.182500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8944d8fb009e'
down_revision = 'a5ad0487ce36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
