"""empty message

Revision ID: 696f0afadf92
Revises: 
Create Date: 2023-04-20 17:21:59.036022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696f0afadf92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caller',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=512), nullable=False),
    sa.Column('push_token', sa.VARCHAR(length=512), nullable=False),
    sa.Column('ip', sa.VARCHAR(length=512), nullable=False),
    sa.Column('actuality_dttm', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caller')
    # ### end Alembic commands ###
